# Generated by Django 3.0.2 on 2020-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
