# Generated by Django 3.0.2 on 2020-08-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200831_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
