# Generated by Django 3.0.2 on 2020-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200831_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default='none', upload_to='videos'),
        ),
    ]
