# Generated by Django 3.0.2 on 2020-08-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200831_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='videos',
        ),
    ]
