# Generated by Django 3.0.2 on 2020-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200831_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.FileField(default='none', upload_to='videos'),
        ),
    ]
