# Generated by Django 3.0.2 on 2020-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200901_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.FileField(default=False, upload_to='videos'),
        ),
    ]
