# Generated by Django 3.0.2 on 2020-08-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200901_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.FileField(blank=True, default=False, upload_to='videos'),
        ),
    ]
